language: objective-c
# should give access to mac osx 10.12
osx_image: xcode8.1

script:
  - brew update
  - brew tap hawkw/x86_64-pc-elf
  - brew tap hamadu/grub
  - travis_wait 120 brew install grub --with-x86_64-pc-elf
